# Generated by Django 4.2.13 on 2024-07-29 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('id',), 'verbose_name': 'корзину', 'verbose_name_plural': 'Корзины'},
        ),
    ]
