# Generated by Django 4.2.13 on 2024-07-15 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_alter_products_discount_alter_products_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('id',), 'verbose_name': 'продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
